Repository 9ITHON/2-giveYouEar-SpeekSee-BE, pull requests merged in 2025-07, with the labels that each got.

#7 3 feature/create script by ai
  src/main/java/com/_ithon/speeksee/domain/Script/controller/ScriptController.java
  src/main/java/com/_ithon/speeksee/domain/Script/entity/DifficultyLevel.java
  src/main/java/com/_ithon/speeksee/domain/Script/entity/Script.java
  src/main/java/com/_ithon/speeksee/domain/Script/entity/ScriptCategory.java
  src/main/java/com/_ithon/speeksee/domain/Script/infra/OpenAiChatClient.java
  src/main/java/com/_ithon/speeksee/domain/Script/port/LlmClient.java
  src/main/java/com/_ithon/speeksee/domain/Script/repository/ScriptRepository.java
  src/main/java/com/_ithon/speeksee/domain/Script/service/ScriptService.java
  src/main/java/com/_ithon/speeksee/global/config/WebClientConfig.java
  src/main/resources/application.yml
Labels: ✨ Feature

#14 13 feature/oauth
  src/main/java/com/_ithon/speeksee/domain/member/entity/AuthProvider.java
  src/main/java/com/_ithon/speeksee/domain/member/entity/Member.java
  src/main/java/com/_ithon/speeksee/global/auth/controller/AuthController.java
  src/main/java/com/_ithon/speeksee/global/auth/controller/OAuthController.java
  src/main/java/com/_ithon/speeksee/global/auth/dto/request/GoogleOAuthRequestDto.java
  src/main/java/com/_ithon/speeksee/global/auth/dto/response/GoogleUserInfoResponseDto.java
  src/main/java/com/_ithon/speeksee/global/auth/dto/response/OAuth2UserInfo.java
  src/main/java/com/_ithon/speeksee/global/auth/jwt/JwtTokenProvider.java
  src/main/java/com/_ithon/speeksee/global/auth/service/AuthService.java
  src/main/java/com/_ithon/speeksee/global/auth/service/AuthServiceImpl.java
  src/main/java/com/_ithon/speeksee/global/auth/service/GoogleOAuth2Client.java
  src/main/java/com/_ithon/speeksee/global/auth/service/OAuth2LoginService.java
  src/main/java/com/_ithon/speeksee/global/auth/service/OAuthService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#15 8 feature/websocket auth
  README.md
  build.gradle
  src/main/java/com/_ithon/speeksee/domain/Script/controller/ScriptController.java
  src/main/java/com/_ithon/speeksee/domain/Script/domain/DifficultyLevel.java
  src/main/java/com/_ithon/speeksee/domain/Script/domain/Script.java
  src/main/java/com/_ithon/speeksee/domain/Script/domain/ScriptCategory.java
  src/main/java/com/_ithon/speeksee/domain/Script/domain/ScriptReadRecord.java
  src/main/java/com/_ithon/speeksee/domain/Script/dto/response/ScriptResponse.java
  src/main/java/com/_ithon/speeksee/domain/Script/dto/resquest/ScriptGenerateRequest.java
  src/main/java/com/_ithon/speeksee/domain/Script/infra/OpenAiChatClient.java
  src/main/java/com/_ithon/speeksee/domain/Script/port/LlmClient.java
  src/main/java/com/_ithon/speeksee/domain/Script/repository/ScriptRepository.java
  src/main/java/com/_ithon/speeksee/domain/Script/service/ScriptService.java
  src/main/java/com/_ithon/speeksee/domain/member/entity/Member.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/config/WebSocketDevConfig.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/config/WebSocketProdConfig.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/controller/PracticeController.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/controller/SttSocketHandler.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/dto/request/PracticeSaveRequest.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/dto/request/PracticeWordDto.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/dto/response/PracticeResponse.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/dto/response/TranscriptResult.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/dto/response/WordInfoDto.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/entity/PracticeWord.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/entity/ScriptPractice.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/client/GoogleStreamingSttClient.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/response/GoogleSttResponseObserver.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/sender/StreamingRequestSender.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/sender/WebSocketErrorSender.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/session/AuthenticatedSession.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/session/SttSessionContext.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/session/SttSessionManager.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/port/StreamingSttClient.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/repository/ScriptPracticeRepository.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/service/PracticeSaveService.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/service/PracticeService.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/service/StreamingSttService.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/util/FinalResponseValidator.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/util/LcsAligner.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/sync/controller/SttTestController.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/sync/infra/GoogleSyncSttClient.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/sync/port/SyncSttClient.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/sync/service/SttService.java
  src/main/java/com/_ithon/speeksee/global/auth/jwt/JwtTokenProvider.java
  src/main/java/com/_ithon/speeksee/global/infra/exception/GlobalExceptionHandler.java
  src/main/java/com/_ithon/speeksee/global/infra/exception/SpeekseeException.java
  src/main/java/com/_ithon/speeksee/global/infra/exception/code/ErrorCode.java
  src/main/java/com/_ithon/speeksee/global/infra/exception/entityException/MemberNotFoundException.java
  src/main/java/com/_ithon/speeksee/global/infra/exception/entityException/ScriptNotFoundException.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ✨ Feature

#26 Refactor 코드 개선
  src/main/java/com/_ithon/speeksee/domain/member/entity/Member.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/controller/PracticeController.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/client/GoogleStreamingSttClient.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/repository/ScriptPracticeRepository.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/service/PracticeService.java
  src/main/java/com/_ithon/speeksee/global/infra/exception/GlobalExceptionHandler.java
  src/main/java/com/_ithon/speeksee/global/infra/exception/code/ErrorCode.java
  src/main/java/com/_ithon/speeksee/global/infra/exception/entityException/PracticeNotFoundException.java
Labels: 🔨 Refactor

#35 feat(statistics): 통계 기능 초기 구현 (연습 수/정확도/점수 조회) 및 QueryDSL 도입
  .gitignore
  build.gradle
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/practice/controller/PracticeController.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/practice/dto/request/PracticeSaveRequest.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/practice/dto/request/PracticeWordDto.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/practice/dto/response/PracticeResponse.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/practice/entity/PracticeWord.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/practice/entity/ScriptPractice.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/practice/service/PracticeSaveService.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/practice/service/PracticeService.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/controller/StatisticsController.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/dev/DummyPracticeDataInitializer.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/dto/CumulativeScoreDto.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/dto/DailyAccuracyDto.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/dto/DailyPracticeCountDto.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/dto/MaxAccuracyTrendDto.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/dto/MonthlyAccuracyDto.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/dto/MonthlyPracticeCountDto.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/dto/PracticeCountResponse.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/dto/WeeklyAccuracyDto.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/dto/WeeklyPracticeCountDto.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/entity/PeriodType.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/repository/ScriptPracticeRepository.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/repository/ScriptPracticeRepositoryCustom.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/repository/ScriptPracticeRepositoryImpl.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/service/StatisticsService.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/util/LabelConverter.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/util/ScoreUtil.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/config/WebSocketDevConfig.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/config/WebSocketProdConfig.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/dto/response/TranscriptResult.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/handler/SttSocketHandler.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/client/GoogleStreamingSttClient.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/response/GoogleSttResponseObserver.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/repository/ScriptPracticeRepository.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/sync/controller/SttTestController.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/sync/infra/GoogleSyncSttClient.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/sync/port/SyncSttClient.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/sync/service/SttService.java
  src/main/java/com/_ithon/speeksee/global/config/QuerydslConfig.java
  src/main/java/com/_ithon/speeksee/global/infra/exception/GlobalExceptionHandler.java
Labels: ✨ Feature

#42 Dev
  src/main/java/com/_ithon/speeksee/domain/member/dto/request/SignUpRequestDto.java
  src/main/java/com/_ithon/speeksee/domain/member/dto/response/MemberInfoResponseDto.java
  src/main/java/com/_ithon/speeksee/domain/member/entity/Level.java
  src/main/java/com/_ithon/speeksee/domain/member/entity/Member.java
  src/main/java/com/_ithon/speeksee/domain/member/service/LevelTestProcessor.java
  src/main/java/com/_ithon/speeksee/domain/member/service/LevelTestService.java
  src/main/java/com/_ithon/speeksee/domain/script/controller/ScriptController.java
  src/main/java/com/_ithon/speeksee/domain/script/domain/Script.java
  src/main/java/com/_ithon/speeksee/domain/script/dto/response/ScriptResponse.java
  src/main/java/com/_ithon/speeksee/domain/script/repository/ScriptRepository.java
  src/main/java/com/_ithon/speeksee/domain/script/service/ScriptService.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/handler/SttSocketHandler.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/client/GoogleStreamingSttClient.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/response/GoogleSttResponseObserver.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/session/AuthenticatedSession.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/session/SttSessionContext.java
  src/main/java/com/_ithon/speeksee/global/seed/InitScriptData.java
Labels: ✨ Feature

#44 38-Fix: 레벨 테스트 모드 누락 응답 처리 및 누적 로직 개선
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/practice/entity/PracticeMode.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/util/LabelConverter.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/statistics/util/ScoreUtil.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/dto/response/TranscriptResult.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/handler/SttSocketHandler.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/client/GoogleStreamingSttClient.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/response/GoogleSttResponseObserver.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/session/AuthenticatedSession.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/session/SttSessionContext.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/infra/session/SttSessionManager.java
  src/main/java/com/_ithon/speeksee/domain/voicefeedback/streaming/service/StreamingSttService.java
Labels: 🐞 BugFix
